apiVersion: v1
kind: Pod
spec:
  nodeSelector:
    cloud.google.com/gke-nodepool: jenkins-builders
  tolerations:
  - key: "dedicated"
    operator: "Equal"
    value: "jenkins-builders"
    effect: "NoSchedule"
  serviceAccountName: jenkins
  containers:
  - name: nodejs
    image: node:hydrogen-alpine3.21
    command:
      - cat
    tty: true
    resources:
      requests:
        cpu: "1"
      limits:
        memory: "3Gi"
        cpu: "2"

