apiVersion: v1
kind: Pod
spec:
  nodeSelector:
    cloud.google.com/gke-nodepool: jenkins-builders
  tolerations:
  - key: "dedicated"
    operator: "Equal"
    value: "jenkins-builders"
    effect: "NoSchedule"
  serviceAccountName: jenkins
  containers:
  - name: playwright
    image: mcr.microsoft.com/playwright:v1.56.1-noble
    command:
      - cat
    tty: true
    resources:
      requests:
        cpu: "1"
        memory: "2Gi"
      limits:
        cpu: "2"
        memory: "4Gi"

